"""Public file-management API for AI-3.0."""

from .compressor import CompressionResult, compress_tdms, compress_tdms_to_storage
from .fingerprint import (
    Digest,
    FileFingerprint,
    fingerprint_file,
    payload_fingerprint,
    payload_sha256,
    sha256_file,
    stored_fingerprint,
)
from .sample_discovery import (
    DiscoveredSample,
    SampleDiscoveryResult,
    discover_samples,
    discover_tdms_samples,
    discover_wav_samples,
    load_sample_profile,
)
from .scanner import (
    IMPORT_SOURCE_SUFFIXES,
    REGISTERED_SUFFIXES,
    ScanEntry,
    ScanIssue,
    ScanResult,
    detect_file_kind,
    is_registered_kind,
    scan_storage,
)
from .storage import (
    DEFAULT_STORAGE_ID,
    DEFAULT_STORAGE_ROOTS,
    InvalidRelativePathError,
    StorageError,
    StorageEscapeError,
    StorageRoots,
    StorageUnavailableError,
    UnknownStorageError,
    load_storage_roots,
    normalize_relative_path,
    resolve_storage_path,
)
from .validators import (
    FileValidationError,
    ValidationResult,
    validate_import_source,
    validate_registered_file,
    validate_tdms,
    validate_wav,
)

__all__ = [
    "CompressionResult",
    "DEFAULT_STORAGE_ID",
    "DEFAULT_STORAGE_ROOTS",
    "Digest",
    "DiscoveredSample",
    "FileFingerprint",
    "FileValidationError",
    "IMPORT_SOURCE_SUFFIXES",
    "InvalidRelativePathError",
    "REGISTERED_SUFFIXES",
    "SampleDiscoveryResult",
    "ScanEntry",
    "ScanIssue",
    "ScanResult",
    "StorageError",
    "StorageEscapeError",
    "StorageRoots",
    "StorageUnavailableError",
    "UnknownStorageError",
    "ValidationResult",
    "compress_tdms",
    "compress_tdms_to_storage",
    "detect_file_kind",
    "discover_samples",
    "discover_tdms_samples",
    "discover_wav_samples",
    "fingerprint_file",
    "is_registered_kind",
    "load_sample_profile",
    "load_storage_roots",
    "normalize_relative_path",
    "payload_fingerprint",
    "payload_sha256",
    "resolve_storage_path",
    "scan_storage",
    "sha256_file",
    "stored_fingerprint",
    "validate_import_source",
    "validate_registered_file",
    "validate_tdms",
    "validate_wav",
]
